version: "3"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-trump}
      POSTGRES_USER: ${DB_USER:-vladimir}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
    volumes:
      - dbData:/var/lib/postgres
    ports:
      - "${PORT_DB:-5432}:5432"
    networks:
      - qnorst


volumes:
  dbData:
    driver: local

networks:
  qnorst:
    driver: bridge